# Generated by Django 4.1.2 on 2022-10-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="trial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("gender", models.CharField(max_length=50)),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("time_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
