# Generated by Django 4.1.2 on 2022-10-20 21:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("note", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="time_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="time_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=200)),
                (
                    "short_description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("time_created", models.DateTimeField(auto_now_add=True)),
                ("time_updated", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="note.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="description",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("time_updated", models.DateTimeField(auto_now=True)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="note.topic"
                    ),
                ),
            ],
        ),
    ]
