# Generated by Django 4.1.2 on 2022-10-20 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("note", "0002_category_time_created_category_time_updated_topic_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="description",
            name="description",
            field=models.TextField(max_length=2000),
        ),
    ]
