# Generated by Django 4.1.2 on 2022-10-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("note", "0004_description_bookmark"),
    ]

    operations = [
        migrations.AlterField(
            model_name="description",
            name="bookmark",
            field=models.CharField(max_length=1, null=True),
        ),
    ]
