# Generated by Django 4.1.2 on 2022-10-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("note", "0005_alter_description_bookmark"),
    ]

    operations = [
        migrations.AddField(
            model_name="description",
            name="image",
            field=models.ImageField(default=1, upload_to=None),
            preserve_default=False,
        ),
    ]
