# Generated by Django 4.1.2 on 2022-10-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("note", "0007_alter_description_bookmark"),
    ]

    operations = [
        migrations.AlterField(
            model_name="description",
            name="image",
            field=models.ImageField(default="", upload_to="note/img"),
        ),
    ]
